# --------------------------------------------------------------------------------------------------
# GLOBAL CONFIGURATION
global:
  extraDeploy: []

# --------------------------------------------------------------------------------------------------
# GENERAL CONFIGURATION
extraDeploy: []
