{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v -}}
{{- $p := $main.persistence -}}

{{- if $p.enabled -}}
{{- if not $p.useHostpath -}}
{{- $pvc := $p.pvc -}}
--- # --------------------------------------------------------------------------------- PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden.fullname" . }}-data
  labels:
    {{- include "vaultwarden.defaultLabels" . | nindent 4 }}
    {{- include "vaultwarden.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $main.labels 
                          $pvc.labels) ) | nindent 4 }}
  annotations:
    {{- include "vaultwarden.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $main.annotations 
                          $pvc.annotations) ) | nindent 4 }}
spec:
  {{- with $pvc.accessModes }}
  accessModes:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ $pvc.size | quote }}
  storageClassName: {{ include "vaultwarden.firstOf" (
                        dict "items" ( list $global.storageClassName 
                                            $pvc.storageClassName )) }}
  {{- with $pvc.volumeName }}
  volumeName: {{ . | quote }}
  {{- end }}
{{- end -}}
{{- end -}}