{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.controller -}}
{{- $crb := $main.rbac.crb -}}

--- # --------------------------------------------------------------------------------- ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certmanager.fullname" . }}-controller
  labels:
    app: controller
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $crb.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $crb.annotations ) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certmanager.fullname" . }}-controller
subjects:
  - name: sa-{{ include "certmanager.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
--- # --------------------------------------------------------------------------------- ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certmanager.fullname" . }}-controller-issuers
  labels:
    app: controller
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $crb.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $crb.annotations ) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certmanager.fullname" . }}-controller-issuers
subjects:
  - name: sa-{{ include "certmanager.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
--- # --------------------------------------------------------------------------------- ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certmanager.fullname" . }}-controller-ingress-shim
  labels:
    app: controller
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $crb.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $crb.annotations ) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certmanager.fullname" . }}-controller-ingress-shim
subjects:
  - name: sa-{{ include "certmanager.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
--- # --------------------------------------------------------------------------------- ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certmanager.fullname" . }}-controller-clusterissuers
  labels:
    app: controller
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $crb.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $crb.annotations ) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certmanager.fullname" . }}-controller-clusterissuers
subjects:
  - name: sa-{{ include "certmanager.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
--- # --------------------------------------------------------------------------------- ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certmanager.fullname" . }}-controller-challenges
  labels:
    app: controller
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $crb.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $crb.annotations ) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certmanager.fullname" . }}-controller-challenges
subjects:
  - name: sa-{{ include "certmanager.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
--- # --------------------------------------------------------------------------------- ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certmanager.fullname" . }}-controller-certificatesigningrequests
  labels:
    app: controller
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $crb.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $crb.annotations ) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certmanager.fullname" . }}-controller-certificatesigningrequests
subjects:
  - name: sa-{{ include "certmanager.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
--- # --------------------------------------------------------------------------------- ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certmanager.fullname" . }}-controller-certificates
  labels:
    app: controller
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $crb.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $crb.annotations ) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certmanager.fullname" . }}-controller-certificates
subjects:
  - name: sa-{{ include "certmanager.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
--- # --------------------------------------------------------------------------------- ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certmanager.fullname" . }}-controller-approve:cert-manager-io
  labels:
    app: controller
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $crb.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $crb.annotations ) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certmanager.fullname" . }}-controller-approve:cert-manager-io
subjects:
  - name: sa-{{ include "certmanager.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount