{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.controller -}}
{{- $sa := $main.rbac.serviceAccount -}}

--- # --------------------------------------------------------------------------------- ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ include "certmanager.fullname" . }}-controller
  labels:
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $sa.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $sa.annotations ) ) | nindent 4 }}
{{- with $sa.automountServiceAccountToken }}
automountServiceAccountToken: {{ . }}
{{- end }}
