{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v -}}
{{- $wl := $main.workload -}}
{{- $pod := $main.pod -}}

{{- if (eq (include "vaultwarden.workloadKind" ( dict "kind" $wl.kind )) "Pod") -}}
--- # --------------------------------------------------------------------------------- Pod
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  annotations:
    {{- include "vaultwarden.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $main.annotations 
                          $wl.annotations
                          $pod.annotations) ) | nindent 4 }}
  labels: 
    {{- include "vaultwarden.selectorLabels" . | nindent 4 }}
    {{- include "vaultwarden.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $main.labels 
                          $wl.labels
                          $pod.labels) ) | nindent 4 }}
spec:
  {{- include "vaultwarden.pod" . | nindent 2 }}
{{- end -}}