apiVersion: v2
name: argocd-crds
description: A Helm chart for deploying argocd's Custom Resource Definitions (CRDs).
type: application
version: 1.0.1
home: "https://github.com/jnnkrdb/helm-charts"
maintainers:
- name: jnnkrdb
  url: https://github.com/jnnkrdb
keywords:
- argoproj
- argocd
- gitops
- cd
- continuous-deployment
- crds
dependencies:
- name: common
  repository: "https://jnnkrdb.github.io/helm-charts"
  version: 1.0.1
