{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.redis -}}
{{- $svc := $main.service -}}

--- # --------------------------------------------------------------------------------- NetworkPolicy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.fullname" . }}-redis
  labels:
    app.kubernetes.io/component: redis
    {{- include "common.defaultLabels" . | nindent 4 }}
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels ) ) | nindent 4 }}
  annotations:
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations ) ) | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: redis
      {{- include "common.defaultSelectorLabels" . | nindent 4 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: server
              {{- include "common.defaultSelectorLabels" . | nindent 14 }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: repo-server
              {{- include "common.defaultSelectorLabels" . | nindent 14 }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: application-controller
              {{- include "common.defaultSelectorLabels" . | nindent 14 }}
      ports:
        - port: {{ $svc.ports.tcp.port }}
          protocol: TCP