apiVersion: v2
name: easyaudit
description: A Helm chart for deploying easy-audit.
type: application
version: 1.0.3
appVersion: 1.0.0
kubeVersion: ">=1.25.0-0"
home: "https://github.com/jnnkrdb/helm-charts"
sources:
- "https://github.com/jnnkrdb/easy-audit"
maintainers:
- name: jnnkrdb
  url: https://github.com/jnnkrdb
keywords:
- easy-audit
- kubernetes
- audit
- logging
dependencies:
- name: common
  repository: "https://jnnkrdb.github.io/helm-charts"
  version: 1.0.1
