{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.cainjector -}}
{{- $wl := $main.workload -}}
{{- $pod := $main.pod -}}

{{- if (eq (include "common.workloadKind" ( dict "kind" $wl.kind )) "Pod") -}}
--- # --------------------------------------------------------------------------------- Pod
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "common.fullname" . }}-cainjector
  labels:
    app: cainjector
    {{- include "common.defaultLabels" . | nindent 4 }}
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels 
                          $wl.labels) ) | nindent 4 }}
  annotations:
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations 
                          $wl.annotations) ) | nindent 4 }}
spec:
  {{- include "cainjector.pod" . | nindent 2 }}
{{- end -}}