{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.webhook -}}
{{- $cr := $main.rbac.cr -}}

--- # --------------------------------------------------------------------------------- ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "certmanager.fullname" . }}-webhook
  labels:
    app: webhook
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $cr.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $cr.annotations ) ) | nindent 4 }}
rules:
# -------------------------------------------------------------------------------------------------------------------- cert-manager-webhook:subjectaccessreviews
  - apiGroups: [ "authorization.k8s.io" ]
    resources: [ "subjectaccessreviews" ]
    verbs: [ "create" ]