{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.webhook -}}
{{- $crb := $main.rbac.crb -}}

--- # --------------------------------------------------------------------------------- ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certmanager.fullname" . }}-webhook:subjectaccessreviews
  labels:
    app: webhook
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $crb.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $crb.annotations ) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certmanager.fullname" . }}-webhook:subjectaccessreviews
subjects:
  - name: sa-{{ include "certmanager.fullname" . }}-webhook
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount