{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.webhook -}}

--- # --------------------------------------------------------------------------------- Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "certmanager.fullname" . }}-webhook
  labels:
    app: webhook
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations ) ) | nindent 4 }}
rules:
# -------------------------------------------------------------------------------------------------------------------- cert-manager-webhook:dynamic-serving
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    resourceNames:
      - {{ include "certmanager.fullname" . }}-webhook-ca
    verbs: [ "get", "list", "watch", "update" ]
  # It's not possible to grant CREATE permission on a single resourceName.
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "create" ]