{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.webhook -}}

--- # --------------------------------------------------------------------------------- RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "certmanager.fullname" . }}-webhook
  labels:
    app: webhook
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations ) ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "certmanager.fullname" . }}-webhook
subjects:
  - kind: ServiceAccount
    name: sa-{{ include "certmanager.fullname" . }}-webhook
    namespace: {{ .Release.Namespace }}