{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.webhook -}}

--- # --------------------------------------------------------------------------------- Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.fullname" . }}-webhook
  labels:
    app: webhook
    {{- include "common.defaultLabels" . | nindent 4 }}
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels ) ) | nindent 4 }}
  annotations:
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations ) ) | nindent 4 }}
rules:
# -------------------------------------------------------------------------------------------------------------------- core / secrets
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    resourceNames:
      - {{ include "common.fullname" . }}-webhook-ca
    verbs: [ "get", "list", "watch", "update" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "create" ]