{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.webhook -}}
{{- $wl := $main.workload -}}
{{- $pod := $main.pod -}}

{{- if (eq (include "certmanager.workloadKind" ( dict "kind" $wl.kind )) "Pod") -}}
--- # --------------------------------------------------------------------------------- Pod
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "certmanager.fullname" . }}-webhook
  labels:
    app: webhook
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels 
                          $wl.labels) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations 
                          $wl.annotations) ) | nindent 4 }}
spec:
  {{- include "webhook.pod" . | nindent 2 }}
{{- end -}}