{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.argocd -}}
{{- $sec := (index $main "argocd-secret") -}}

{{- if $main.enabled -}}
{{- if $sec.enabled -}}
--- # --------------------------------------------------------------------------------- Secret
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/component: notifications-controller
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels ) ) | nindent 4 }}
  annotations:
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.annotations  
                          $v.annotations ) ) | nindent 4 }}
type: Opaque
{{- with $sec.data }}
data:
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- if $sec.stringData }}
stringData:
  {{- range $key, $value := $sec.stringData }}
  {{- if $value }}
  {{ $key }}: {{ tpl ($value | toString) $ | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end -}}
{{- end -}}