{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.notificationscontroller -}}
{{- $cm := (index $main.config "argocd-notifications-cm") -}}


{{- if $main.enabled -}}
{{- if $cm.enabled -}}
--- # --------------------------------------------------------------------------------- ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  labels:
    app.kubernetes.io/component: notifications-controller
    {{- include "common.defaultLabels" . | nindent 4 }}
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels
                          $main.labels  ) ) | nindent 4 }}
  annotations:
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.annotations  
                          $v.annotations
                          $main.annotations ) ) | nindent 4 }}
{{- with $cm.data }}
data:
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end -}}
{{- end -}}