{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.notificationscontroller -}}

--- # --------------------------------------------------------------------------------- Secret
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  labels:
    app.kubernetes.io/component: notificationscontroller
    {{- include "common.defaultLabels" . | nindent 4 }}
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels
                          $main.labels  ) ) | nindent 4 }}
  annotations:
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.annotations  
                          $v.annotations
                          $main.annotations ) ) | nindent 4 }}
type: Opaque
