{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.notificationscontroller -}}
{{- $rbac := $main.rbac -}}

{{- if $main.enabled -}}
--- # --------------------------------------------------------------------------------- ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ include "common.fullname" . }}-notificationscontroller
  labels:
    app.kubernetes.io/component: notifications-controller
    {{- include "common.defaultLabels" . | nindent 4 }}
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $rbac.labels ) ) | nindent 4 }}
  annotations:
    {{- include "common.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $rbac.annotations ) ) | nindent 4 }}
{{- with $rbac.serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: {{ . }}
{{- end }}
{{- end -}}
