{{- $v := .Values -}}
{{- $global := $v.global -}}
{{- $main := $v.cainjector -}}
{{- $cr := $main.rbac.cr -}}

--- # --------------------------------------------------------------------------------- ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "certmanager.fullname" . }}-cainjector
  labels:
    app: cainjector
    {{- include "certmanager.defaultLabels" . | nindent 4 }}
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.labels 
                          $v.labels 
                          $main.labels
                          $cr.labels ) ) | nindent 4 }}
  annotations:
    {{- include "certmanager.keyValues" ( 
        dict "kvs" ( list $global.annotations 
                          $v.annotations 
                          $main.annotations
                          $cr.annotations ) ) | nindent 4 }}
rules:
  - apiGroups: [ "cert-manager.io" ]
    resources: [ "certificates" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "get", "create", "update", "patch" ]
  - apiGroups: [ "admissionregistration.k8s.io" ]
    resources: [ "validatingwebhookconfigurations", "mutatingwebhookconfigurations" ]
    verbs: [ "get", "list", "watch", "update" ]
  - apiGroups: [ "apiregistration.k8s.io" ]
    resources: [ "apiservices" ]
    verbs: [ "get", "list", "watch", "update" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "get", "list", "watch", "update" ]