name: Lint and Test Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/lint-test.yaml'
      - '.github/workflows/workflow.chart-tests.yaml'
  pull_request:
    paths:
      - 'charts/**'
      - '.github/workflows/lint-test.yaml'
      - '.github/workflows/workflow.chart-tests.yaml'

jobs:
  chart-tests:
    uses: ./.github/workflows/workflow.chart-tests.yaml
    with:
      run-lint: true
      run-template: true
      run-unittests: true
      run-policytests: true
      run-integrationtests: true
      charts-path: charts
      chart-test-yaml: ct.yaml
      templatevalues-subdir: .values
      unittests-subdir: .unittests
      unittests-filefilter: '*.unit.yaml'
      policies-subdir: .policies
      policies-general-dir: policies
